// Everything the site's own search boxes (homepage band, nav-bar search,
// homepage inline search) can find, across every real content type, not
// just the 76 principles. Categories match the site's own nav menu labels
// exactly, so grouped search results read as an extension of that same
// menu rather than a separate taxonomy. Principles are pulled from
// APPLY_PRINCIPLES (apply-data.js) rather than duplicated here a third
// time; load apply-data.js before this file.
var SEARCH_INDEX = (typeof APPLY_PRINCIPLES !== 'undefined' ? APPLY_PRINCIPLES.map(function (p) {
  return { title: p.title, category: 'Principles', url: 'principles.html#' + p.id, blurb: p.blurb };
}) : []).concat([

  // ---------- The Science Behind ----------
  { title: 'Why does raw selvedge denim feel like better quality than jeans that actually fit?', category: 'The Science Behind', url: 'science-behind.html#japanese-selvedge-denim', blurb: "Narrower fabric, a rough unfinished hem, no stretch, and a price tag several times a regular pair, on paper this should read as worse, not better. Four real mechanisms explain why Japanese selvedge denim doesn't.", keywords: 'meaningless differentiation ikea effect scarcity halo effect' },
  { title: 'Why does the same coffee taste sweeter from one side of this pink cup than the other?', category: 'The Science Behind', url: 'science-behind.html#dual-lip-coffee-cup', blurb: 'A 200ml porcelain filter cup with a thin lip on one side, a thick lip on the other, and a soft pink glaze, three real design choices built on one idea: change the cue, not the coffee.', keywords: 'crossmodal correspondence cross-modal sensory' },
  { title: "Why does Afterpay's four-dot progress bar make the same $100 feel smaller?", category: 'The Science Behind', url: 'science-behind.html#pay-in-4-checkout', blurb: 'Afterpay\'s own checkout button: pick "Pay in 4" and a $100 order becomes four payments of $25, shown as four dots on the button itself rather than a single total.', keywords: 'chunking present bias zero price effect payment transparency bnpl' },
  { title: "How do you trust a shirt you've never tried on?", category: 'The Science Behind', url: 'science-behind.html#proper-cloth-and-son-of-a-tailor', blurb: "Proper Cloth's Smart Sizes quiz and free remake, and Son of a Tailor's Ideal Size quiz and signed, named-sewer hangtag: two made-to-order companies solving the same trust problem in different ways.", keywords: 'take-the-best heuristic loss aversion operational transparency ikea effect social proof' },
  { title: "Why does GoalSaver's 4.75% bonus feel like money you'd be losing, not money you haven't earned yet?", category: 'The Science Behind', url: 'science-behind.html#goalsaver-bonus-interest', blurb: "CommBank's GoalSaver: a savings account paying 5.00% p.a. made up of a permanent 0.25% base rate plus a 4.75% bonus that only applies in a calendar month with at least one deposit and no withdrawals at all.", keywords: 'loss aversion clawback precommitment devices mental accounting goal gradient effect' },
  { title: "How does Up Bank's behavioural design pay off for both the bank and its customers?", category: 'The Science Behind', url: 'science-behind.html#up-bank-teardown', blurb: 'Follow an Up customer through the app in the order these features actually show up, and the same design instinct repeats at every stop: a saving habit earned, locked in, named, watched, applied to a home loan and a $5 coffee alike, and now to recurring bills through Essentials.', keywords: 'loss aversion clawback precommitment devices mental accounting goal gradient effect chunking scarcity social proof pain of paying' },
  { title: 'Why does a $2.50 fries deal come with a chance to win free food for life?', category: 'The Science Behind', url: 'science-behind.html#macca-golden-deal', blurb: "McDonald's Australia app: a $2.50 large fries deal with a prize draw for free food for life attached, and no stated odds anywhere on the screen.", keywords: 'probability weighting chance to win prize draw framing effect mcgold card' },
  { title: 'Why do you have to be "into double denim" to win a better savings rate?', category: 'The Science Behind', url: 'science-behind.html#bankwest-interesting-rate', blurb: "Bankwest's Easy Saver: a monthly draw for an 11.50% p.a. \"Interesting Rate,\" a relabelled consolation rate for everyone who doesn't win, and an app-download step framed as something you'd lose by skipping.", keywords: 'probability weighting framing effect loss aversion savings lottery prize-linked savings' },

  // ---------- Field Sessions ----------
  { title: 'Teaching Year 8/9 students the maths their brains skip', category: 'Field Sessions', url: 'sessions.html#high-school-money-talk', blurb: 'From a real money talk at a high school: why do smart 14-year-olds still think "50% off" means they\'re saving money?' },
  { title: 'Finding the "Phase 2" every roadmap quietly skips', category: 'Field Sessions', url: 'sessions.html#mapping-outcome-logic', blurb: 'Could you defend the arrow from your last initiative to actual profit, out loud, right now?' },
  { title: 'Why telling customers what\'s "safe to spend" can make them spend more', category: 'Field Sessions', url: 'sessions.html#safe-to-spend-backfire', blurb: "A well-intentioned feature that backfired: what if the reassuring number on the home screen is what's causing the overspending?" },
  { title: 'Why your best pilot is the one most likely to lose its voltage', category: 'Field Sessions', url: 'sessions.html#voltage-effect-scaling', blurb: 'What if using your very best people is exactly what makes a pilot fail to scale?' },
  { title: 'What my dentist got right, without ever hearing the term "behavioural economics"', category: 'Field Sessions', url: 'sessions.html#dentist-visit', blurb: 'How many of these would still be running if nobody in the building could name a single one?' },
  { title: 'Where Behavioural Economics Actually Sits', category: 'Field Sessions', url: 'sessions.html#defining-behavioural-economics', blurb: 'Why does behavioural economics refuse to pick a side between the spreadsheet and the mystery?' },
  { title: 'The Metric That Lied To The Whole Room', category: 'Field Sessions', url: 'sessions.html#watching-the-metric-lies', blurb: 'What if the metric that convinced you it worked would have gone up anyway?' },
  { title: 'Why $350,000 suddenly looks cheap', category: 'Field Sessions', url: 'sessions.html#agile-australia-10x-product', blurb: 'From the Agile Australia conference stage: why does $6,495,000 make $350,000 feel like a bargain?' },

  // ---------- Digital & Product Experiments ----------
  { title: 'Does naming a savings pocket keep the money there?', category: 'Experiments', url: 'experiments.html#named-pockets', blurb: 'If "Savings Pocket 2" became "Save for Phone," would less of it get spent?', keywords: 'mental accounting salience' },
  { title: 'Does tradeoff transparency work between products, not just within one?', category: 'Experiments', url: 'experiments.html#product-comparison-tradeoff-transparency', blurb: 'CBA proved this comparing credit cards to each other. Does it hold comparing credit to other ways to pay?' },
  { title: 'Does a costly, specific apology beat a generic one after a service failure?', category: 'Experiments', url: 'experiments.html#costly-specific-apology', blurb: 'List found a costly apology paid for itself once, and backfired the moment it repeated. How do you design for both?', keywords: 'reciprocity' },
  { title: 'Does a great digital home loan lift home loan trust everywhere else, too?', category: 'Experiments', url: 'experiments.html#digital-home-loan-halo', blurb: 'Built on the Halo Effect: why would a customer who never opens the new digital home loan still be more likely to sign one at a branch?' },
  { title: 'Does a home loan rate of 5.99% get remembered as a 5% loan, not almost 6%?', category: 'Experiments', url: 'experiments.html#left-digit-home-loan-rate', blurb: 'A 5.99% home loan rate is really almost 6%. Does it get compared like a 5% one instead?', keywords: 'left digit bias charm pricing 99 pricing' },
  { title: 'Does explaining why a fee went up change whether customers think it\'s fair?', category: 'Experiments', url: 'experiments.html#fee-change-fairness-explanation', blurb: 'Kahneman, Knetsch and Thaler proved this with a hypothetical snow shovel. Does it hold for a real bank fee notice?', keywords: 'perceived fairness dual entitlement' },
  { title: 'Does telling customers the payment-transparency heuristic change what they actually spend?', category: 'Experiments', url: 'experiments.html#payment-heuristic-messaging', blurb: 'Prelec and Simester proved credit blunts the felt cost of paying. Does telling a customer that, at the right moment, blunt it back?', keywords: 'credit card premium' },
  { title: 'Does framing account setup as one set to complete finish more setups?', category: 'Experiments', url: 'experiments.html#pseudo-set-account-setup', blurb: 'Built on Pseudo-Set Framing: Barasz, John, Keenan, and Norton proved an arbitrary group of items feels incomplete and pulls people to finish it.' },
  { title: 'Does a prize-linked feature beat an equal-value rate bonus for new deposits?', category: 'Experiments', url: 'experiments.html#prize-linked-savings-feature', blurb: 'A lab study found people defer more for a lottery-style payout than a guaranteed one of identical expected value.', keywords: 'savings lottery prize-linked savings PLSA save to win' },
  { title: 'Does a chance at 0% increase home loan applications more than the guaranteed discount alone?', category: 'Experiments', url: 'experiments.html#home-loan-prize-draw', blurb: 'A genuinely competitive guaranteed discount plus a separate chance at 0% p.a. for 12 months, testing Probability Weighting on a home loan rather than a savings rate.' },
  { title: 'Does showing progress through a home loan appointment booking increase completion?', category: 'Experiments', url: 'experiments.html#home-loan-appointment-progress', blurb: 'A pre-filled loyalty card sped people up with the identical distance left to go. Does simply showing progress do that?', keywords: 'goal gradient effect progress bar' },
  { title: 'Does timing a savings increase to a raise beat asking for it right now?', category: 'Experiments', url: 'experiments.html#smart-save-at-next-raise', blurb: 'Save More Tomorrow tied the increase to an employer\'s known pay schedule.', keywords: 'smart defaults automatic escalation' },
  { title: 'Does explaining why a feature was removed reduce the backlash?', category: 'Experiments', url: 'experiments.html#explain-before-retiring-feature', blurb: 'Not Enough Choice says restriction without explanation triggers reactance. Does one added sentence actually change what customers do?' },
  { title: 'Does naming the freedom to decline raise opt-in on a real ask?', category: 'Experiments', url: 'experiments.html#free-to-skip-round-up-savings', blurb: 'A street request nearly quintupled once people were told they were free to refuse.', keywords: 'reactance not enough choice psychological reactance' },
  { title: 'Does framing a tier as restricted increase upgrade interest?', category: 'Experiments', url: 'experiments.html#restricted-tier-framing', blurb: 'The founding reactance study proved restriction increases desire. Does that hold when the restriction is a real, honest eligibility gate?', keywords: 'not enough choice' },
  { title: 'Does completing a responsible credit action change how someone redeems reward points right after?', category: 'Experiments', url: 'experiments.html#virtuous-act-reward-redemption-choice', blurb: 'Same points, same redemption screen. Does having just done the responsible thing make someone more likely to pick the indulgent option?', keywords: 'licensing effect moral licensing' },
  { title: 'Does a savings commitment made a week in advance survive contact with the actual moment?', category: 'Experiments', url: 'experiments.html#advance-vs-in-moment-savings-commitment', blurb: 'Same customer, same decision, one week apart. Does deciding in advance land on a different number than deciding once the money\'s actually there?', keywords: 'present bias hyperbolic discounting' },
  { title: 'Does showing what you\'ve already paid reduce comparison shopping at renewal?', category: 'Experiments', url: 'experiments.html#sunk-cost-renewal-screen', blurb: "Arkes and Blumer's field study proved a real sunk cost changes real behaviour.", keywords: 'sunk cost fallacy' },
  { title: 'Does a truthful daily-equivalent price increase annual-plan uptake, even with the total shown right next to it?', category: 'Experiments', url: 'experiments.html#pad-annual-checkout', blurb: "Gourville's studies reframed a cost as pennies a day instead of stating the total.", keywords: 'temporal reframing pennies a day' },
  { title: 'Does stating one discount on a bundle beat splitting the identical discount across its parts?', category: 'Experiments', url: 'experiments.html#bundle-level-discount-framing', blurb: 'Yadav and Monroe found a saving stated on the bundle carries more weight than the same saving split across items.', keywords: 'bundling' },
  { title: 'Does naming the real dollar cost of repeat late fees cut how much someone borrows next?', category: 'Experiments', url: 'experiments.html#bnpl-late-fee-disclosure', blurb: 'For a BNPL provider: a real field test on payday loans found stating dollar fees over time cut future borrowing by 11%.', keywords: 'disclosure backfire' },
  { title: 'Does trimming a 10-option investing menu to 3 curated ones change how evenly people spread their money?', category: 'Experiments', url: 'experiments.html#curated-investment-menu', blurb: 'Benartzi and Thaler found real retirement savers split contributions evenly across however many funds a plan offered. Does a real investing app menu do the same?', keywords: 'diversification heuristic 1/n heuristic naive diversification' },
  { title: 'Does directing a tax refund to pay down a credit card increase spending right after?', category: 'Experiments', url: 'experiments.html#tax-refund-debt-payoff-spending', blurb: 'Built on the Licensing Effect: does confirming a paydown happened make someone spend more on everything else in the weeks after?' },
  { title: 'Does showing a customer where a cashback rate ranks against similar spenders pull them toward the lower-paying card?', category: 'Experiments', url: 'experiments.html#cashback-rank-vs-raw-rate', blurb: "Built on Positional Concern: does knowing one card leaves you ahead of similar customers beat the card that simply pays more?" },
  { title: 'Does a benevolence-framed decline reduce how harshly customers judge the bank after a loan rejection?', category: 'Experiments', url: 'experiments.html#loan-decline-benevolence-framing', blurb: 'Built on Shooting the Messenger: does opening an automated decline with one sentence of genuine care change how a customer feels about the bank?' },
  { title: 'Does a printed annual member guide increase renewal more than a digital-only version?', category: 'Experiments', url: 'experiments.html#printed-vs-digital-member-guide', blurb: 'Touch is proven to raise how much people value a physical object. Does that show up in an actual renewal decision a year later?', keywords: 'endowment effect credit card premium tactile premium' },
  { title: 'Does asking a customer to state their own plan reduce no-shows on a home loan appointment?', category: 'Experiments', url: 'experiments.html#home-loan-appointment-plan-prompt', blurb: 'Gollwitzer and Brandstätter proved a specific plan beats a bare intention. Four prompts, tested for both a phone and an in-branch appointment: does stating a plan cut no-shows either way?', keywords: 'implementation intentions if-then planning' },

  // ---------- Reading the Research ----------
  { title: 'How strong is that evidence, actually?', category: 'Reading the Research', url: 'evidence-strength.html', blurb: 'A field guide to causal evidence: a ranked ladder from raw correlation to randomised trials, framed around product and commercial decisions, with the selection-bias traps that sink careful-looking analysis.' },
  { title: 'Policy-based evidence, not evidence-based policy', category: 'Reading the Research', url: 'policy-based-evidence.html', blurb: "John List's case for flipping how governments build evidence: design the test around the constraints of scale from the start, instead of scaling a pilot that was never built to survive it." },
  { title: "Don't say the E-word", category: 'Reading the Research', url: 'dont-say-the-e-word.html', blurb: "Why organisations flinch at the word 'experiment,' rename it a pilot or trial, and often quietly drop the control group along with the label, on John List's real advice and its cost." },
  { title: 'How you pay changes what you spend', category: 'Reading the Research', url: 'how-you-pay-changes-what-you-spend.html', blurb: "Cash, debit, and credit aren't just three ways to move the same money. Two real studies and the mechanism connecting them: why the payment method itself changes how much gets spent." },
  { title: 'The test was real. The conclusion wasn\'t.', category: 'Reading the Research', url: 'small-sample-big-claim.html', blurb: "Thirteen real cases of experiments that didn't lie and still misled, each a real claim resting on a small sample: samples too small to see the effect, results stretched into a universal law, and tests run on a guess with no theory behind the metric they moved." },
  { title: "The lottery you can't lose.", category: 'Reading the Research', url: 'savings-lottery.html', blurb: 'Prize-linked savings accounts pay no guaranteed interest, only a chance at a prize sized to your balance, and the deposit itself is never at risk. Real programmes moved millions into savings.', keywords: 'prize-linked savings PLSA save to win no-lose lottery' },
  { title: 'Behavioural economics vs. behavioural science vs. psychology vs. UX', category: 'Reading the Research', url: 'nobody-owns-a-bias.html', blurb: 'Nobody owns a bias: behavioural economics, psychology, applied behavioural science, and UX all draw on the same small set of findings. Sometimes the name survives the trip between them. Sometimes it doesn\'t.' },
  { title: 'Six moves behind every pricing page', category: 'Reading the Research', url: 'six-moves-behind-every-pricing-page.html', blurb: 'Temporal reframing, chunking, anchoring, bundling, sunk cost, and zero price. Six real, cited mechanisms, and the pricing-page patterns that run on each one.' },
  { title: 'Not testing is still a bet', category: 'Reading the Research', url: 'not-testing-is-still-a-bet.html', blurb: "A pre-vs-post number isn't a lesser form of measurement, it usually isn't measurement at all. Real cases where it said one thing and a real experiment said another." },
  { title: 'Every default decides who pays for doing nothing', category: 'Reading the Research', url: 'every-default-decides-who-pays.html', blurb: 'Opt-in, opt-out, forced choice, timed defaults, and personalised defaults aren\'t one lever. A researched spectrum of all five, with the real studies, the numbers, and the one famous result that didn\'t survive a better test.' },
  { title: 'The fine print nobody reads.', category: 'Reading the Research', url: 'the-fine-print-nobody-reads.html', blurb: 'Standard disclosures get read by almost nobody, and when they are read, disclosing a conflict of interest can make the advice behind it worse, not better.' },
  { title: "You're already doing behavioural economics.", category: 'Reading the Research', url: 'you-are-already-doing-behavioural-economics.html', blurb: 'Every pricing page and product screen already makes choice-architecture decisions. Eight already-cited mechanisms, from anchoring to bundling.' },
  { title: 'Proximity gets mistaken for merit', category: 'Reading the Research', url: 'proximity-gets-mistaken-for-merit.html', blurb: 'A 1946 MIT housing lottery and a 2022 machine-learning study of the MLB draft, seventy years apart, found the identical bias: living close to a decision-maker predicts the outcome, even when it has nothing to do with merit.' },
  { title: 'Printing costs more than digital. The paper copy still wins.', category: 'Reading the Research', url: 'the-tactile-premium.html', blurb: "Digital is cheaper to send, every time. Three real, cited studies on touch, reading comprehension, and the tactile premium people place on physical objects explain why organisations still mail the paper copy anyway." },
  { title: "Breaking a form into steps changes how it feels. It doesn't always change how it performs.", category: 'Reading the Research', url: 'breaking-a-form-into-steps.html', blurb: "Progress Flow (steps and a progress bar) and Progressive Load (one continuous page) both borrow real psychology, chunking and the goal-gradient effect, but six studies ranked by fidelity show the same pattern doing nothing on a desktop and backfiring on a phone." },
  { title: "AI gets over-trusted until it errs once. Then it gets under-trusted for good.", category: 'Reading the Research', url: 'ai-over-trusted-then-under-trusted.html', blurb: "Automation bias and algorithm aversion are the same AI trust miscalibration pointed in opposite directions, and keeping a human in the loop doesn't reliably fix either one. Ten real, cited studies on coding assistants, clinical AI, and everyday knowledge work." },
  { title: "The coin has no memory. The streak still feels real.", category: 'Reading the Research', url: 'the-coin-has-no-memory.html', blurb: "What a fair coin can teach you about statistics: the gambler's fallacy, what a p-value actually says, and why the smallest sample in any ranking always looks the most extreme. Real, cited studies including Tversky and Kahneman's law of small numbers." },
  { title: 'Every program runs on a theory. Most never write it down.', category: 'Reading the Research', url: 'every-program-runs-on-a-theory.html', blurb: 'Program theory is the decades-old evaluation discipline underneath every logic model: why a program fails for one of two very different reasons, shown on a real program that made crime worse while working exactly as designed, and one that got the theory right from day one.' },
  { title: 'Backfires have six different causes. They all look the same.', category: 'Reading the Research', url: 'backfires-have-six-different-causes.html', blurb: 'Six real interventions, a daycare late fee, a campus bottled-water ban, Scared Straight, an energy-bill letter, a rat bounty, and a charity reminder, each backfired for a different, specific reason: crowding out, substitution, a wrong theory of the audience, a hidden subgroup, a gamed proxy, and an uncounted second number.' },

  // ---------- Natural Experiments ----------
  { title: 'How do you prove distance biased 30,000 draft picks when nobody can randomly assign where a scout lives?', category: 'Natural Experiments', url: 'natural-experiments.html#mlb-draft-propinquity', blurb: 'A real test of the Propinquity Effect at professional scale: a 2022 study used machine learning to control for skill in the MLB draft, then measured whether living closer to a scouting director still predicted getting picked.' },

  // ---------- Apply It ----------
  { title: 'Apply It', category: 'Apply It', url: 'apply.html', blurb: 'Turn a principle or a problem into an experiment. Answer a few questions about what\'s going wrong and get matched to the specific principles that explain it.' }
]);
